name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v2

      # Step 2: Install Node
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "23.x"

      # Step 3: Install Newman and Reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Step 4: Create Directory for Results
      - name: Make Directory for results
        run: mkdir -p testResults

      # Step 5: Run Postman Collection and Generate Report
      - name: Run POSTMAN collection
        run: |
          newman run store.collection.json -r htmlextra \
          --reporter-htmlextra-export testResults/htmlreport.html \
          --reporter-htmlextra-darkTheme

      # Step 6: Copy Report to Docs Folder for GitHub Pages
      - name: Copy Report to Docs Folder
        run: |
          mkdir -p docs
          cp testResults/htmlreport.html docs/index.html

      # Step 7: Upload Test Results as Artifact (Optional)
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
