name: Run Newman Collection

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install Newman and HTML Extra Reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Step 4: Make Directory for Report Results
      - name: Create Directory for Results
        run: mkdir -p testResults

      # Step 5: Start Local Server (if applicable)
      - name: Start Local API Server
        run: npm run tern-on-api &

      # Step 6: Run Newman Collection and Generate Report
      - name: Run Newman Collection
        run: |
          newman run ./petstore.collection.json \
          -r htmlextra \
          --reporter-htmlextra-export testResults/index.html \
          --reporter-htmlextra-darkTheme

      # Step 7: Upload Test Report as Artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: TestReport
          path: testResults
